services:
  - type: web
    name: voice-mind-api
    plan: free
    env: docker
    rootDir: backend
    region: oregon
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///./voice_stress.db
